### ISSUE TITLE
Investigate `sqlserver` driver

### ISSUE THREAD

**Issue by AlekSi** [go-reform/reform#104]
https://github.com/denisenkom/go-mssqldb offers two drivers. Currently, we use only `mssql`. The only documented difference between it and `sqlserver` is [statement parameters syntax](https://github.com/denisenkom/go-mssqldb#statement-parameters). Are there other differences? Should we support both?

**Comment by AlekSi** [comment]
@AlekseyMartynov Can you look into it?

**Comment by AlekseyMartynov** [comment]
Here is what I discovered.

Parameter parsing is the only difference. The other driver ("sqlserver") is free from rewriting SQL expressions, but it seems that the use of `sql.Named` is required (available only in 1.8?)

For example, instead of 
```
q.Exec(query, record.PKValue())
```
it should be
```
q.Exec(query, sql.Named("p1", record.PKValue()))
```

`Dialect` will need to know which kind of parameter its driver accepts

**Comment by AlekseyMartynov** [comment]
Please ignore my previous comment. 
The "sqlserver" driver works just fine, with few code changes: https://github.com/AlekseyMartynov/reform/commit/c7891d9a8d83089c80f2935a886ecb66a1aabc83

The point I initially missed is "magic" placeholder names: `@p1` ... `@pN`

**Comment by AlekSi** [comment]
Ok, I guess we can add it as another dialect then.
