### ISSUE TITLE
Support for MS SQL

### ISSUE THREAD

**Issue by AlekSi** [go-reform/reform#11]
3 steps:
1. Add dialect for MS SQL. That should be easy.
2. Fix reform and/or tests. Should be easy too, and likely not even required.
3. The hardest step: add Travis CI integration. MS SQL should be provisioned only on builder with specified target.

The first one who will send a working pull request will receive a squishable gopher from me and @GolangShow!

**Comment by AlekseyMartynov** [comment]
Hi @AlekSi 

I have some results in this regard. It seems it's going to be somewhat harder :smile: 

* Dialect needs an abstraction for `LIMIT 1` clause, because in SQL Server they use a completely different syntax (`SELECT TOP 1`)
* Some tests insert explicit identities, in SQL Server this requires temporary enabling and disabling `IDENTITY_INSERT` (info https://msdn.microsoft.com/en-us/library/ms188059.aspx). The list of test cases: `TestInTransaction`, `TestInsertMultiWithPrimaryKeys`, `TestInsertWithPrimaryKey`
* Updating identities is [not supported](http://stackoverflow.com/questions/751522/how-to-change-identity-column-values-programmatically/1188102#comment26928004_1188102) too (`TestUpdateColumns`)
* In the podcast you say that SQL Server now runs on Linux, however we currently don't have much info except announcements and ability to apply for the preview.
* If everything else gets solved, it's better to add 3rd `LastInsertIdMethod` to use the `OUTPUT INSERTED` syntax (discussion: http://stackoverflow.com/a/1427650)

My code: https://github.com/AlekseyMartynov/reform/commit/26a7f015c1eb703d0dc7b4201d19515c6702ff8c

**Comment by AlekSi** [comment]
* Abstraction for `LIMIT 1` / `SELECT TOP 1` is fine. `SELECT TOP 1` looks like the most straight-forward way to implement limit.
* We can enable/disable `IDENTITY_INSERT` in tests, that's fine. 
* We can skip some test data in `TestUpdateColumns`.
* We can use AppVeyor for Windows builds, they have [SQL Server installed](https://www.appveyor.com/docs/services-databases).
* Let's try it.

Good job!

**Comment by AlekseyMartynov** [comment]
> We can skip some test data in TestUpdateColumns.

Wouldn't it be more correct to forbid using pk column in `UpdateColumns`?
Queries like `update foo set id=1 where id=1` don't look useful.

> We can use AppVeyor for Windows builds, they have SQL Server installed.

I know AppVeyor quite well and can work on this item.

**Comment by AlekSi** [comment]
#32, #33.

**Comment by AlekSi** [comment]
#32 is fixed.

**Comment by AlekseyMartynov** [comment]
Cool. `TestUpdateColumns` passes now on MS SQL

**Comment by AlekseyMartynov** [comment]
Done in #35:
* `LIMIT` vs `SELECT TOP`
* `IDENTITY_INSERT` in tests
* `OUTPUT INSERTED` last insert id method
* AppVeyor + Coveralls (requires changing repo token)

Build log: https://ci.appveyor.com/project/AlekSi/reform/build/20
Coverage: https://coveralls.io/github/AlekseyMartynov/reform
